// Short paraphrases, grouped by the source used to check them.
// Keep each fact self-contained and preserve species-specific qualifications.
const groups = [
  {
    source: "https://animals.sandiegozoo.org/animals/frog-and-toad",
    facts: [
      "Toads belong to the same animal order as frogs: Anura.",
      "Frogs can absorb water through their skin.",
      "A frog's skin lets oxygen pass through it.",
      "Some frogs walk or run instead of hopping.",
      "Frogs live on every continent except Antarctica.",
      "Many tadpoles eat algae before they become insect-eating adults.",
      "A tadpole absorbs its tail as it turns into a frog.",
      "The change from tadpole to frog is called metamorphosis.",
      "Waxy tree frogs spread a waxy coating over their skin to reduce water loss.",
      "A frog's visible eardrum is the round patch beside its eye.",
    ],
  },
  {
    source: "https://nationalzoo.si.edu/animals/african-clawed-frog",
    facts: [
      "African clawed frogs use their front fingers to push food into their mouths.",
      "An African clawed frog has hardened tips on three toes of each hind foot.",
      "African clawed frogs have no tongues.",
      "African clawed frogs sense water vibrations through a system along their sides.",
      "On land, African clawed frogs crawl rather than hop.",
      "African clawed frog tadpoles filter food from the water.",
      "Female African clawed frogs are much larger than males.",
      "African clawed frogs can change their skin's shade to match their surroundings.",
      "Male African clawed frogs make clicking calls underwater.",
      "African clawed frog eggs stick to underwater objects with a jelly coating.",
    ],
  },
  {
    source: "https://nationalzoo.si.edu/animals/panamanian-golden-frog",
    facts: [
      "Panamanian golden frogs wave their arms to communicate.",
      "Panamanian golden frogs hunt during daylight.",
      "A Panamanian golden frog's yellow skin warns predators about its toxins.",
      "Female Panamanian golden frogs usually grow larger than males.",
      "Panamanian golden frogs from wet forests grow larger than those from dry forests.",
      "Panamanian golden frogs lay their eggs in strings in shallow water.",
      "Panamanian golden frog tadpoles have belly suckers that help them hold on in streams.",
      "Newly hatched Panamanian golden frog tadpoles are white.",
      "Young Panamanian golden frogs turn yellow as they mature.",
      "Panamanian golden frogs use sight to find small insects and other prey.",
    ],
  },
  {
    source: "https://nationalzoo.si.edu/animals/lemur-leaf-frog",
    facts: [
      "Lemur leaf frogs turn brown when they become active at night.",
      "Lemur leaf frogs usually walk slowly along branches.",
      "A thick black outline surrounds each eye of a lemur leaf frog.",
      "Lemur leaf frogs have no webbing between their toes.",
      "Female lemur leaf frogs are usually larger than males.",
      "A male lemur leaf frog's warning call is a short tick.",
      "Male lemur leaf frogs can push intruders off their perches.",
      "Lemur leaf frogs lay eggs on leaves above water.",
      "Rain can trigger lemur leaf frog larvae to leave their eggs and drop into water.",
      "Even lemur leaf frog tadpoles can change color between day and night.",
    ],
  },
  {
    source: "https://nationalzoo.si.edu/animals/poison-frogs",
    facts: [
      "The food poison frogs eat in the wild supplies their skin toxins.",
      "Poison frogs fed non-toxic insects in human care do not develop the same poisons.",
      "Poison frogs can live for more than ten years in human care.",
      "Poison frogs usually hunt in daylight.",
      "Some poison frog parents carry a whole group of tadpoles on their backs.",
      "Poison frog courtship can last for hours.",
      "Many poison frogs lay their eggs among damp fallen leaves.",
      "Poison frog parents visit or guard their eggs as they develop.",
      "Poison frog tadpoles can eat insect larvae as well as plant matter.",
      "Only three poison frog species have documented use as a source of hunting dart poison.",
    ],
  },
  {
    source: "https://animaldiversity.org/accounts/Lithobates_sylvaticus/",
    facts: [
      "Wood frogs can survive with part of their bodies frozen.",
      "A wood frog's heart stops beating during winter freezing.",
      "Wood frog tadpoles can recognize their relatives.",
      "A wood frog's call can sound like a duck's quack.",
      "Wood frogs have a dark face patch that looks like a mask.",
      "Wood frogs often return to the same area to breed.",
      "Wood frogs breed in pools without fish.",
      "Wood frogs live as far north as Alaska.",
      "Female wood frogs are usually larger than males.",
      "Wood frog eggs hatch more slowly in cold water.",
    ],
  },
  {
    source: "https://animaldiversity.org/accounts/Lithobates_catesbeianus/",
    facts: [
      "American bullfrog tadpoles can spend several years in water before they become frogs.",
      "A male American bullfrog's eardrum is larger than its eye.",
      "Male American bullfrogs wrestle to defend stretches of shoreline.",
      "An American bullfrog's call can carry more than a kilometer.",
      "American bullfrogs can eat other bullfrogs.",
      "American bullfrogs wait for prey to come close before striking.",
      "American bullfrogs prefer warm, still water.",
      "Male American bullfrogs have yellow throats during the breeding season.",
      "American bullfrog tadpoles mostly graze on water plants.",
      "An American bullfrog can weigh about half a kilogram.",
    ],
  },
  {
    source: "https://animaldiversity.org/accounts/Agalychnis_callidryas/",
    facts: [
      "Red-eyed tree frogs have orange feet.",
      "Red-eyed tree frogs shelter beneath broad leaves in hot or dry weather.",
      "Red-eyed tree frogs are active at night.",
      "Female red-eyed tree frogs tend to be larger than males.",
      "Red-eyed tree frogs lay eggs beneath leaves over water.",
      "Red-eyed tree frogs breed during the rainy season.",
      "Young red-eyed tree frogs can change skin color with the time of day.",
      "Red-eyed tree frogs have blue and yellow markings alongside their green bodies.",
      "Male red-eyed tree frogs fight for access to mates.",
      "Red-eyed tree frog tadpoles feed on particles suspended in water.",
    ],
  },
  {
    source: "https://animaldiversity.org/accounts/Dendrobates_auratus/",
    facts: [
      "Green-and-black poison frogs also come in blue-and-black forms.",
      "People introduced green-and-black poison frogs to Hawaii.",
      "Green-and-black poison frogs spend much of their time on the forest floor.",
      "Male green-and-black poison frogs check on their eggs as they develop.",
      "Green-and-black poison frog fathers carry tadpoles to water on their backs.",
      "Mucus helps green-and-black poison frog tadpoles cling to their father's back.",
      "Male green-and-black poison frogs attract mates with trills.",
      "Green-and-black poison frogs hunt with sticky tongues.",
      "Green-and-black poison frogs use their eyesight to catch prey.",
      "Green-and-black poison frogs eat ants that supply chemicals for their skin defenses.",
    ],
  },
  {
    source: "https://animaldiversity.org/accounts/Oophaga_pumilio/",
    facts: [
      "Strawberry poison frogs can be blue, green, or orange as well as red.",
      "Strawberry poison frog mothers give each tadpole its own tiny pool.",
      "Strawberry poison frog tadpoles eat unfertilized eggs from their mother.",
      "Strawberry poison frog tadpoles vibrate their bodies to ask their mother for food.",
      "Male strawberry poison frogs wrestle over territory.",
      "Strawberry poison frogs eat large numbers of ants and mites.",
      "Strawberry poison frogs often climb vines above the forest floor.",
      "Adult strawberry poison frogs are usually less than 2.5 centimeters long.",
      "Strawberry poison frogs are especially active in the morning.",
      "Female strawberry poison frogs often choose mates with a similar body color.",
    ],
  },
  {
    source: "https://animaldiversity.org/accounts/Phyllobates_terribilis/",
    facts: [
      "Golden poison frogs can be mint green or orange.",
      "Young golden poison frogs have dark bodies with pale stripes.",
      "Adult golden poison frogs usually have one solid body color.",
      "Golden poison frogs live near Colombia's Pacific coast.",
      "Golden poison frogs spend their adult lives on the forest floor.",
      "Female golden poison frogs tend to be larger than males.",
      "Golden poison frogs have batrachotoxins in their skin.",
      "A golden poison frog's bright skin warns predators to leave it alone.",
      "Golden poison frogs depend on freshwater pools for their young.",
      "Adult golden poison frogs are roughly five centimeters long.",
    ],
  },
  {
    source: "https://animaldiversity.org/accounts/Pipa_pipa/",
    facts: [
      "Surinam toad young develop in pockets in their mother's back.",
      "Surinam toads emerge from their mother's back as small frogs.",
      "Surinam toads have wide, flattened bodies.",
      "A Surinam toad's fingertips end in small star-shaped structures.",
      "Surinam toads have tiny eyes without eyelids.",
      "Surinam toads have large hind feet that work like flippers.",
      "Surinam toads live in murky ponds and swamps.",
      "Mating Surinam toads turn somersaults in the water.",
      "Surinam toads can lay about 100 eggs during a mating session.",
      "Surinam toads come to the water's surface to breathe air.",
    ],
  },
  {
    source: "https://animaldiversity.org/accounts/Conraua_goliath/",
    facts: [
      "Goliath frogs are the world's largest living frogs.",
      "A goliath frog can weigh more than three kilograms.",
      "Goliath frogs live in Cameroon and Equatorial Guinea.",
      "Goliath frogs live beside fast rivers and waterfalls.",
      "A goliath frog's body can reach about 32 centimeters long.",
      "Goliath frogs have no vocal sacs.",
      "Young goliath frog tadpoles are similar in size to those of much smaller frogs.",
      "Adult goliath frogs sometimes bask on rocks.",
      "Goliath frogs search for food along rivers at night.",
      "A goliath frog's eyes can be nearly 2.5 centimeters across.",
    ],
  },
  {
    source: "https://animaldiversity.org/accounts/Hyla_versicolor/",
    facts: [
      "Gray tree frogs can turn green or brown.",
      "Gray tree frogs usually have a pale patch beneath each eye.",
      "Gray tree frogs hide yellow or orange skin on the undersides of their hind legs.",
      "Gray tree frog toe pads produce mucus that helps them grip smooth surfaces.",
      "Gray tree frogs spend winter under logs, roots, or fallen leaves.",
      "An eastern gray tree frog trills more slowly than a Cope's gray tree frog at the same temperature.",
      "Gray tree frog trills become faster as the air warms.",
      "Gray tree frog tadpoles can detect predators through chemicals in the water.",
      "Injured gray tree frog tadpoles release a chemical alarm signal.",
      "Gray tree frog tadpoles reduce their activity when water predators are nearby.",
    ],
  },
  {
    source: "https://animaldiversity.org/accounts/Pseudacris_crucifer/",
    facts: [
      "Spring peepers have a dark cross-shaped mark on their backs.",
      "Adult spring peepers are often only two to 2.5 centimeters long.",
      "Spring peepers can climb, but often stay near the ground.",
      "Spring peepers prefer breeding ponds without fish.",
      "Spring peepers often breed in pools that dry up later in the year.",
      "Spring peepers are native to eastern North America.",
      "Spring peepers can have brown, gray, or olive skin.",
      "Spring peepers have small discs on their fingers and toes.",
      "Male spring peepers gather by the hundreds at breeding pools.",
      "Spring peepers are among the first frogs to breed after winter.",
    ],
  },
  {
    source: "https://animaldiversity.org/accounts/Rhinella_marina/",
    facts: [
      "Cane toads have large poison glands behind their eyes.",
      "Cane toads have horizontal pupils.",
      "Cane toads lay eggs in long jelly strings.",
      "A cane toad can lay tens of thousands of eggs at once.",
      "Cane toad tadpoles gather in dense groups.",
      "Cane toad tadpoles are small and black.",
      "Cane toad eggs can hatch in as little as two days.",
      "Cane toads have a bony ridge near the snout.",
      "Cane toads have spread to islands through human introductions.",
      "Male cane toads call for mates from still or slow water.",
    ],
  },
  {
    source: "https://animaldiversity.org/accounts/Bombina_orientalis/",
    facts: [
      "Oriental fire-bellied toads have triangular pupils.",
      "An Oriental fire-bellied toad's belly can be red-orange or yellow with dark markings.",
      "Oriental fire-bellied toads can have bright green backs.",
      "Oriental fire-bellied toads have no visible eardrum.",
      "Female Oriental fire-bellied toads are generally larger than males.",
      "Male Oriental fire-bellied toads develop finger pads during the breeding season.",
      "Oriental fire-bellied toads can live around puddles and ditches.",
      "Oriental fire-bellied toads lay eggs on underwater plants.",
      "Male Oriental fire-bellied toads call while floating in shallow water.",
      "An Oriental fire-bellied toad's mating call sounds like a bark.",
    ],
  },
  {
    source: "https://animaldiversity.org/accounts/Scaphiopus_holbrookii/",
    facts: [
      "Eastern spadefoots dig with hard projections on their hind feet.",
      "Eastern spadefoots have vertical pupils.",
      "Eastern spadefoots prefer loose soil that is easy to dig.",
      "Eastern spadefoots breed in temporary pools.",
      "Eastern spadefoots can use flooded roads as breeding sites.",
      "An eastern spadefoot's back stripes can form an hourglass shape.",
      "Eastern spadefoots can give off a musty or peppery smell.",
      "Eastern spadefoots use fallen leaves and twigs to line their burrows.",
      "Eastern spadefoots can live in suburban neighborhoods.",
      "In warm water, eastern spadefoot eggs can hatch within a day.",
    ],
  },
  {
    source: "https://animaldiversity.org/accounts/Eleutherodactylus_coqui/",
    facts: [
      "Coqui frogs hatch as tiny frogs, without a free-swimming tadpole stage.",
      "Coqui frogs are native to Puerto Rico.",
      "A male coqui's call has one part for rivals and another for potential mates.",
      "Male coqui frogs guard their nests even after the young hatch.",
      "Coqui frogs sometimes use abandoned bird nests for their eggs.",
      "Coqui frogs have separate toes without webbing.",
      "Coqui frogs use sticky toe pads to climb leaves and trees.",
      "Coqui frogs at higher elevations tend to grow larger.",
      "Coqui frogs can breed without a pond.",
      "Female coqui frogs are larger than males.",
    ],
  },
  {
    source: "https://animaldiversity.org/accounts/Rhinoderma_darwinii/",
    facts: [
      "Male Darwin's frogs carry developing young in their vocal sacs.",
      "Darwin's frog mothers lay their eggs on damp soil.",
      "Darwin's frog young leave their father's vocal sac as tiny frogs.",
      "Darwin's frogs live in Chile and Argentina.",
      "Darwin's frogs live in temperate forests.",
      "A Darwin's frog has a pointed extension on its nose.",
      "Darwin's frogs can be brown or bright green.",
      "A Darwin's frog has a dark belly with pale spots.",
      "Darwin's frogs eat insects.",
      "Adult Darwin's frogs are only about 2.5 to 3.5 centimeters long.",
    ],
  },
  {
    source: "https://animaldiversity.org/accounts/Pyxicephalus_adspersus/",
    facts: [
      "African bullfrogs wait out dry weather in underground chambers.",
      "Male African bullfrogs grow much larger than females.",
      "An African bullfrog uses hard projections on its hind feet to dig.",
      "African bullfrogs have three tooth-like projections on their lower jaws.",
      "Young African bullfrogs have pale back stripes that fade with age.",
      "Male African bullfrogs defend their eggs.",
      "African bullfrog eggs can hatch in two days.",
      "African bullfrogs breed in temporary water after rain.",
      "Male African bullfrogs fight for positions near the center of breeding groups.",
      "A male African bullfrog's call is a deep whoop.",
    ],
  },
  {
    source: "https://animaldiversity.org/accounts/Lithobates_pipiens/",
    facts: [
      "Northern leopard frogs often wander far from water outside the breeding season.",
      "Northern leopard frogs also go by the name meadow frogs.",
      "Northern leopard frogs can live more than 3,000 meters above sea level.",
      "Northern leopard frogs have pale borders around their dark spots.",
      "A northern leopard frog has a white line along each side of its mouth.",
      "Male northern leopard frogs have two vocal sacs.",
      "Northern leopard frog tadpoles have bellies clear enough to show their coiled intestines.",
      "Northern leopard frogs attach egg clusters to underwater plants.",
      "Female northern leopard frogs usually grow larger than males.",
      "Northern leopard frog eggs swell when they contact water.",
    ],
  },
  {
    source: "https://animaldiversity.org/accounts/Lithobates_clamitans/",
    facts: [
      "Green frogs can be bronze as well as green.",
      "Rare green frogs have blue or orange skin.",
      "Green frogs have raised skin folds that run back from their eyes.",
      "Male green frogs display their yellow throats to warn rivals.",
      "Male green frogs can wrestle over territory for nearly an hour.",
      "Green frogs sometimes move away from water to feed after rain.",
      "Green frogs often avoid areas occupied by American bullfrogs.",
      "A green frog can lay several thousand eggs in one clutch.",
      "Green frog tadpoles often wait through winter before they become frogs.",
      "Green frogs can spend winter underwater if enough oxygen is available.",
    ],
  },
  {
    source: "https://animaldiversity.org/accounts/Lithobates_palustris/",
    facts: [
      "Pickerel frogs can spend winter in limestone caves.",
      "Pickerel frogs sometimes spend winter in abandoned mines.",
      "Pickerel frogs leave the water for fields and woods in warmer months.",
      "Pickerel frogs have paired dark spots along their backs.",
      "Pickerel frogs have a white line on their upper lips.",
      "Pickerel frogs have dark bands across their hind legs.",
      "Male pickerel frogs develop larger thumb pads during the mating season.",
      "Pickerel frogs attach egg clusters to underwater twigs and stems.",
      "Pickerel frog tadpoles can be green, brown, or gray.",
      "Pickerel frogs usually spend about three months as tadpoles.",
    ],
  },
  {
    source: "https://animaldiversity.org/accounts/Lithobates_berlandieri/",
    facts: [
      "Rio Grande leopard frogs can shelter from dry conditions by burrowing.",
      "Rio Grande leopard frogs often live along streams.",
      "Rio Grande leopard frogs can use cattle tanks and irrigation canals as habitat.",
      "Rio Grande leopard frogs stay active year-round when temperatures allow.",
      "Rio Grande leopard frogs have irregular dark spots with lighter borders.",
      "The raised folds on a Rio Grande leopard frog's back bend inward near its hind legs.",
      "Older Rio Grande leopard frogs often have mottled chins.",
      "Rio Grande leopard frogs have angular snouts.",
      "Rio Grande leopard frog tadpoles have gold irises with tiny black flecks.",
      "Rio Grande leopard frog tadpoles have rounder snouts than adults.",
    ],
  },
] as const;

export const frogFacts: readonly { text: string; source: string }[] = groups.flatMap(({ source, facts }) =>
  facts.map((text) => ({ text, source }))
);
