/** Shared by full reviews, incremental reviews, and read-only specialists. */
export const UI_REUSE_REVIEW = `**UI reuse pass (when the reviewed delta changes UI).**

- Inspect changed page templates, inline markup/render functions, feature components, navigation, and user-visible copy, not only newly added component files. Read the applicable UI rules and component inventory. Search for the existing composed components and read their implementations plus a current, rule-compliant caller before deciding that a replacement fits. Reusing low-level buttons or cards does not establish reuse of a KPI, table, picker, or page layout.
- Keep a compact internal reuse map for each changed UI pattern: changed file, existing composed component and caller inspected, and reuse/extension/justified-new/unresolved. Check whether existing props and slots cover the requirement; consider a small compatible extension before recommending a new shared abstraction. A feature wrapper that composes existing UI is valid. Do not demand that all markup become components or ban new components whose behavior the existing UI cannot support.
- Check composition as well as imports: metrics use the repository's established KPI pattern; tables and widgets use established containers and title/info slots; page actions and filters follow the header convention; explanatory copy follows the help/hover convention. Check page-versus-tab ownership and duplicated navigation against the repository's rules and actual routes. These are inspection questions, not universal design rules: do not hardcode one repository's component names, forbid tabs or refresh buttons globally, or infer an action's behavior from its label. Trace refresh handlers before claiming they only reload data or trigger work.
- Report a reuse violation only with the applicable written requirement, the changed hunk, an inspected existing component/caller that covers the need (or a concrete compatible extension), and the resulting inconsistency or duplicated behavior. Check exceptions and conflicting guidance. A missing reuse map from the PR author is not itself a code defect. New-file counts, unfamiliar appearance, and personal taste are not evidence. Preserve incremental scope: unchanged UI is context, not a fresh finding. Keep the map in run logs, not a checklist in the posted review.
- Static inspection supports composition and behavior findings; do not claim rendered appearance was verified without browser evidence. Use an available preview under the repository's testing rules when visual evidence is needed. If it is unavailable, state the limitation only where it affects the conclusion; do not invent a visual finding or approve a visual claim from imports alone.`;

export const REVIEW_CONVENTIONS = `**Repository conventions pass (required before findings or a no-issues decision).**

- After checkout and the authoritative diff read, identify the affected areas. Read the root and applicable nested AGENTS.md files (or their agent-specific equivalents), then explicitly read the relevant rules and current docs they reference. Include hidden instruction directories. A link or @path is a discovery lead, not evidence that its contents were loaded. Follow applicable scope/glob conditions and cross-area contracts; do not load the whole doc tree.
- Use the repository's stated authority order. Unless it specifies otherwise: explicit rules and strategy, current documentation, generated artifacts/current definitions, then comparable code. Existing code, old migrations, closed PRs, and remembered learnings do not override a written rule. Check documented exceptions and superseded patterns before proposing a change. Do not perform live writes to establish current state.
- Assess the changed code against those sources as well as correctness. A documented requirement is reviewable even when it concerns naming, composition, architecture, or documentation; it is not an undocumented style preference. For each convention finding, cite the rule's path and section or lines, the changed code, the applicable requirement, and its concrete consequence. Calibrate severity to that consequence; do not turn every convention violation into a merge blocker. Drop personal preferences, permitted exceptions, and unrelated pre-existing violations. In incremental reviews, apply current guidance to the new delta and regressions it introduces or amplifies; do not repeat unchanged prior feedback.
- Before returning incremental findings, re-read the new delta separately from the full PR diff. Keep the two diff sources distinctly labeled in tool output. Identify the exact new-delta hunk that introduces or amplifies each candidate and explain that causal link. A violation visible only in the full PR diff is insufficient. Drop candidates that cannot be traced to the new delta, even if they are serious or were not mentioned in prior feedback.
- Emit a compact **Consulted repository guidance** record in your internal assistant output (retained in the run logs): each source path and section actually read, the affected area it governs, and any missing or conflicting source. Update it if later investigation adds sources. Distinguish rules from examples and background. If no guidance exists, record where you checked. Never claim a source was consulted merely because it was linked or appeared in a search result. Surface unresolved conflicts or missing guidance in the review only when they materially limit the conclusion; do not invent a rule or silently resolve a conflict by copying nearby code.

${UI_REUSE_REVIEW}`;
