import { formatMcpToolRef, type AgentId } from "../external.ts";

export const REVIEW_LENSES = {
  A: { name: "Control and failure signals", trigger: "Decision gates, validation, exceptions, fallbacks, or success/failure classification change.", evidence: "Trace concrete inputs and failure terminals through returned results to the downstream decision. Distinguish success, empty, partial, failed, and unknown." },
  B: { name: "Parity and propagation", trigger: "An identifier, interface, scope/filter, shared mapping, or value passed between components changes.", evidence: "Trace the authoritative producer through every affected consumer and sibling to the final sink, including defaults and transforms. Search beyond changed files." },
  C: { name: "Data semantics", trigger: "Joins, aggregation, identity spaces, pagination, migrations, RPC contracts, grants, or replay/backfill behavior change.", evidence: "Show cardinality and identity assumptions, collection completeness, and forward/replay or retry behavior for the affected contracts." },
  D: { name: "Frontend state", trigger: "Mutation handling, async data, cache keys, drafts, status rendering, listeners, or paged UI collections change.", evidence: "Trace mutations to every affected view/cache and failures to the displayed state. Check scope, races, draft baselines, and collection completeness." },
  E: { name: "Executable procedures", trigger: "CI workflows, shell commands, runnable skill procedures, or artifact handoffs change.", evidence: "Trace each prerequisite from its producer through durable storage to its first consumer, with exact runtime/cwd and failure exits. Inspect pinned tools, not an assumed current version." },
  F: { name: "Lifecycle and recovery", trigger: "State transitions, queues, checkpoints, retries, cancellation, cleanup, or resource ownership change.", evidence: "Trace entry state, durable writes, side effects, success and failure exits, retry/resume, and cleanup order. Account for coupled state and ownership on each exit." },
} as const;

export type ReviewLens = keyof typeof REVIEW_LENSES;
export const BASE_REVIEW_PASSES = ["correctness", "conventions", "documentation", "verification"] as const;

export function singleSessionReviewPrompt(agentId: AgentId): string {
  const checkpoint = formatMcpToolRef(agentId, "review_checkpoint");
  const read = formatMcpToolRef(agentId, "read_file");
  return `**Single-session review coverage.** Perform all passes yourself in this Codex session. Do not dispatch subagents or start another model session. This is a harness restriction, not a model capability limit. Repository skills that describe a review fleet supply applicable checks; their dispatch instructions do not apply here. Review code without editing it. Continue authorized inspection and checkpoint work without waiting for clarification; when missing information prevents a conclusion, record the limitation.

First read the incremental delta when supplied and the diff table of contents to establish scope. Load applicable repository governance and the domain-specific references it names. If the repository supplies a governance manifest builder, run it through the existing MCP shell sandbox with the exact \`changedFilesPath\` returned by checkout_pr, never the formatted diff or a reconstructed file list. The manifest covers the full PR for conservative guidance discovery. Plan before rereading the full patch: the harness can reuse prior reads only after validating current guidance.

Call \`${checkpoint}\` with action=plan and checkout_pr's \`reviewId\`. Supply the manifest_path, or a concrete no_manifest_reason identifying where you checked if the repository has no provider. Decide selected/not_applicable for EVERY lens A–F, citing the risk shape in the change or a concrete exclusion reason. Select by behavior, not confidence or line count; select when uncertain. Inspect written domain rules before filling in assumptions.

The plan returns \`analysisScope\` and unread raw-diff ranges. When scope is \`incremental\`, a complete prior review has been verified against the exact baseline, base commit and current guidance: investigate the delta and its affected consumers; do not redo unchanged review work. When scope is \`full\`, prior coverage was missing, incompatible or incomplete: finish the outstanding full-PR review, including previously unreviewed issues outside the latest delta. Deduplicate existing feedback in either case. Old pass evidence is never imported as a fresh conclusion; execute current passes for this scope.

Read every remaining range with \`${read}\`: use \`path\` and optional \`start_line\`, then follow \`next_cursor\` until \`complete_through_line\` reaches the range end (or \`eof\`). A page ending mid-line is normal; continue the cursor to finish it. The harness counts only delivered content. Use \`unifiedDiffPath\` for complete raw content and \`diffPath\` for inline-comment anchors; GitHub can omit large patches from the numbered display. Read related context again whenever needed, even when its prior diff coverage was reused. Call action=status to get remaining ranges and passes. Never try to mark unread ranges complete with a shell read or a checkpoint assertion.

${Object.entries(REVIEW_LENSES).map(([id, lens]) => `- **${id}: ${lens.name}.** Trigger: ${lens.trigger} Evidence: ${lens.evidence}`).join("\n")}

Execute the baseline correctness, conventions, and documentation passes, every selected lens, and every applicable sweep returned by the plan. Use action=record to checkpoint completed work in batches; each row names its pass ID, status, and evidence (reference, trace steps, outcome). Trace rows must name concrete code, inputs, consumers, or execution results; "checked, looks good" is not evidence. Explicitly account for nonexistent trace dimensions in the outcome. A sweep hit is a candidate: inspect documented exemptions and explain its disposition. Record failed commands as incomplete, never as an empty result. Invariants are owned by their named lint/tests; procedures and out-of-scope checks are accounted for automatically. Review changed enforcement itself for correctness without duplicating unrelated CI.

Use focused verification to resolve a concrete uncertainty: reproduce a suspected failure or run the smallest relevant check. Do not install dependencies or run broad suites just for reassurance. After a check passes, repeat or broaden it only when changed code, a failure, or an unresolved concern warrants it. Required sweeps and coverage still apply.

Finish with the verification pass: challenge every candidate against source, exceptions, concrete impact, and the exact causal delta; discard disproven claims and deduplicate by root cause. Include non-anchored concerns when supported. Severity depends on impact, not the lens. Zero findings needs evidence too. This is a second pass in the SAME session, not an independent review.

Recover according to the failure, not a fixed retry count:
- Cut-off shell output is recoverable pagination: read its saved output file with \`${read}\`, or read the source file directly. More pages are progress, not failed retries.
- A missing package manager or dependency is setup work: inspect the affected package's packageManager field, lockfile and CI procedure (which may be in a subdirectory), provision that pinned tool through the supported setup route, install only the dependencies needed for focused verification, then rerun the check. Respect shell restrictions and repository setup rules.
- A check naming a missing source path is a broken check configuration: inspect current tracked paths and the rule's intent. Use an equivalent current-path check only when its scope is provably preserved; otherwise record the broken check as incomplete. Never interpret an execution error as zero matches.
- Retry a transient service error after its indicated delay. For denied access or persistent setup failure, record the attempted recovery and what is still unavailable, and finish independent review work before publishing.

Before EVERY completion path, including a formatting-only incremental acknowledgement, complete the checkpoint. These obligations replace any instruction to skip deeper work: non-applicable lenses may be excluded with reasons, but baseline passes still run. Continue while read pages or repairable setup steps remain; diff size and an initial failed command are not reasons to stop. If required work remains blocked after appropriate recovery, call action=incomplete: \`reason\` contains internal failure details and attempts, while \`public_summary\` is one short plain-language sentence naming the unchecked work and its blocker. Publish a useful summary and verified inline findings without approval or a clean verdict; the harness adds the incomplete status without replacing that summary. Do not put checkpoint IDs, “authoritative reading”, “governance sweeps”, or retry bookkeeping in the public summary. A new checkout invalidates coverage when its scope changes. Detailed evidence stays in the run log.`;
}
